
### CREATE

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "usuario": "novo",
    "senha": "novo",
    "status": 1
}


### FindAll

GET http://localhost:3000/usuarios


### UPDATE
PUT http://localhost:3000/usuarios/6
Content-Type: application/json

{
    "usuario": "novo",
    "senha": "novo",
    "status": 1
}
